name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  tests:
    name: "Test: PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Verify MySQL version
        run: mysql --host 127.0.0.1 -uroot -p1234 -e "STATUS"

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit -v

      - name: Run tests with DAMADoctrineTestBundle
        run: vendor/bin/phpunit -v --configuration phpunit-dama-doctrine.xml.dist

  prefer-lowest-tests:
    name: "Test: PHP ${{ matrix.php }}, --prefer-lowest"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Verify MySQL version
        run: mysql --host 127.0.0.1 -uroot -p1234 -e "STATUS"

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-lowest-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --prefer-lowest --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit -v

      - name: Run tests with DAMADoctrineTestBundle
        run: vendor/bin/phpunit -v --configuration phpunit-dama-doctrine.xml.dist

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify MySQL version
        run: mysql --host 127.0.0.1 -uroot -p1234 -e "STATUS"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: xdebug

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-coverage-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: Run code coverage
        run: vendor/bin/phpunit -v --coverage-text --coverage-clover=coverage.clover

      - name: Run code coverage with DAMADoctrineTestBundle
        run: vendor/bin/phpunit -v --coverage-text --coverage-clover=dama-coverage.clover

      - name: Send code coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
          php ocular.phar code-coverage:upload --format=php-clover dama-coverage.clover

  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout code
          uses: actions/checkout@v1

      -   name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: 7.4
            coverage: none

      -   name: Validate composer.json
          run: composer validate --strict --no-check-lock

  cs-check:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout code
          uses: actions/checkout@v1

      -   name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: 7.4
            coverage: none

      -   name: Install dependencies
          run: wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer.phar

      -   name: Check CS
          run: php php-cs-fixer.phar fix --dry-run --diff
